# Site
repository: HarkjinDev/HarkjinDev.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: 문학진
title: Information Security
email: m.harkjin@gmail.com

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: HarkjinDev

# About Section
# about_title: About Me
about_profile_image: images/profile2.jpg
about_content: | 
  안녕하세요. 저는 <mark>주인의식</mark> <mark>책임감</mark> <mark>소통</mark>을 가장 중요하게 여기는 정보보안 전문가를 꿈꾸는 문학진입니다. <br />
  
  업무를 할 때는 제 업무뿐만 아니라, 회사가 원하는 방향이 무엇인지 전체를 생각하는 <mark>주인의식</mark>을 가지고 일을 하는 스타일입니다. <br />
  
  4년의 전기정비 일을 하면서 책임감을 가지고 일을 하는 것을 배웠습니다.<br />
  사소한 거 하나라도 보안의 위험을 놓치지 않는다는 <mark>책임감</mark>을 항상 가지고 일을 하는 사람이 되고자 노력합니다.<br />
  
  보안은 다양한 직군의 동료들과 끊임없는 <mark>소통</mark>을 해야, 더욱더 안전한 환경을 만들 수 있다고 생각합니다.<br />
  <br />
  <em>이런 업무를 해보고 싶습니다.</em> <br />
  • 보안 관제 운영(보안 이벤트 로그 분석 활동 및 대응)<br />
  • 취약점 진단 및 침해사고 대응(취약점 진단 침투 테스트 및 대응)<br />
  • 각종 보안 시스템 구축 및 운영 관리(인프라 및 보안솔루션 등)<br />
  • 정보보호 계획 및 운영, 정보보호 인증 관련 업무(ISMS-P, ISO27001, 국정원 관리실태평가 등)<br />
  <br />
  <em>미래를 위한 계획</em> <br/>
  • AWS Speciality Security(~2022) <br />
  • CPPG 개인정보관리사(~2022) <br />
  • ISMS-P 인증심사원(~2023) <br />

content:
# Skills
  - title: Skills
    layout: text
    content: |
      <ul>
      <li>IT Infrastructure Implementation/Management (Windows/Linux Server, IPS, IDS, VPN, Firewall, WAF, Cisco Router/Switch)</li>
      <li>Penetration Test(MetaSploit)</li>
      <li>Network Security Traffic Analysis(Wireshark, Snort, ELK, Splunk, Graylog)</li>
      <li>Programming(Python, Bash, Powershell, C++)</li>
      <li>AWS(Gamelift, DynamoDB, API Gateway, EC2, LightSail)</li>
      </ul>
      
# Experience
  - title: Experience
    layout: list 
    content:
      - layout: left
        title: 한국재정정보원
        sub_title: 기획재정사이버안전센터
        caption: 2022-05 ~ Present
        link: https://www.fis.kr/ko
        description: | 
           보안 관제 및 컨설팅
      - layout: left
        title: NH농협은행
        sub_title: 개인정보보호부 (계약직)
        caption: 2021-10 ~ 21-05 (0.7yrs)
        link: https://www.nhbank.com/
        description: | 
           영업점 원격점검, 정보보호 인증 관련 내/외부 점검 및 지도 지원 업무
      - layout: left
        title: 포스코
        sub_title: 전기 정비
        caption: 2013-07 ~ 2017-01 (3.7yrs)
        link: https://www.posco.co.kr/
        description: | 
           전기, 계측 설비 및 시스템의 제어 운영 및 정비

# Study Projects
  - title: Study Projects 
    layout: list 
    content:
      - layout: left
        title: 통합관제시스템 구축
        link: https://github.com/HarkjinDev/Security/tree/main/Write-up/SIEM
        link_text: Link Github
        description: | 
          오픈소스 Security Onion을 사용하여 관제시스템을 구성하였고, 취약한 윈도우 및 리눅스 서버에 시스템 및 웹 취약점 테스트를 진행하고, ELK 및 Splunk를 활용하여 다양한 보안 이벤트를 분석 및 시각화를 하여 보안 관제 운영에 필요한 지식을 습득하고 경험해 보았습니다. <br />
          <mark>ELK</mark> <mark>Splunk</mark> <mark>Saltstack</mark> <mark>Suricata</mark> <mark>Zeek</mark> <mark>Grafana</mark> <mark>Strelka</mark> <mark>Wazuh</mark>
      - layout: left
        title: 랜섬웨어 분석 및 차단 연구
        link: https://github.com/HarkjinDev/Security/tree/main/Write-up/Ransomware
        link_text: Link Github
        description: | 
          Sophos UTM을 구축하여 스팸메일 APT 공격을 메일 필터링으로 차단하고, 차단한 랜섬웨어 악성 프로그램을 ClamAV 및 Cuckoo Sandbox를 활용하여 분석하는 자동화 시스템을 파이썬과 Bash Script로 개발해 보았습니다. <br />
          <mark>Sophos UTM</mark> <mark>ClamAV(Antivirus)</mark> <mark>Cuckoo Sandbox</mark> <mark>Mareware Analysis</mark> <mark>Mail Filtering</mark>
      - layout: left
        title: 주요통신기반시설 기술적 취약점 분석/평가 스크립트 제작
        link: https://github.com/HarkjinDev/Security/tree/main/VulnerabilityAnalysis
        link_text: Link Github
        description: |
          주요통신기반시설 기술적 취약점 분석과 대응 방안 가이드를 토대로 Bash Script로 제작하여 취약점 점검에 대한 지식을 습득하고 경험 해보았습니다. <br />
          <mark>Server/System Management</mark> <mark>Vulnerability Analysis</mark> <mark>Bash script</mark>
      - layout: left
        title: ModSecurity WAF 구축
        link: https://github.com/HarkjinDev/Security/tree/main/ModSecurity
        link_text: Link Github
        description: | 
          ModSecurity WAF와 취약한 웹 서버를 구성하여 OWASP 취약점에 대해 공격을 진행하여 로그를 분석하고 룰 개발을 하면서, 웹 공격에 대한 지식을 습득하고 경험해 보았습니다. <br />
          <mark>WAF</mark> <mark>Apache</mark> <mark>Web Hacking</mark>
      - layout: left
        title: Suricata IDS/IPS 구축
        link: https://github.com/HarkjinDev/Security/tree/main/Suricata
        link_text: Link Github
        description: | 
          Suricata와 취약한 서버들을 구성하여 DOS 및 Web 공격을 진행하여 로그를 분석하고 Snort 룰을 개발하여 차단하면서, 네트워크 및 웹 공격에 대한 지식을 습득하고 경험해 보았습니다. <br />
          <mark>IDS</mark> <mark>IPS</mark> <mark>Snort</mark> <mark>Dos/Web Attacking</mark>
      - layout: left
        title: RDP 취약점 분석 연구
        link: https://github.com/HarkjinDev/Security/tree/main/Write-up/RDP
        link_text: Link Github
        description: | 
          CVE-2019-0708 Bluekeep RDP 취약점에 대한 분석 및 모의해킹 <br />
          <mark>Mareware Analysis</mark> <mark>Vulnerability Analysis</mark> <mark>Penetration Testing</mark>
      - layout: left
        title: Wargame Challenge
        link: <a href='https://github.com/HarkjinDev/Security/tree/main/Reverse/HackMe' target='_blank' style='font-size:14px; text-decoration:none;'>FTZ</a> <br /> <a href='https://github.com/HarkjinDev/Security/tree/main/Reverse/LOB' target='_blank' style='font-size:14px; text-decoration:none;'>LOB(The lord of BOF)</a> 
        description: | 
          <mark>System Hacking</mark> <mark>Reverse Engineering</mark> <mark>BOF</mark>

# Side Projects
  - title: Side Projects 
    layout: list 
    content:
      - layout: left
        title: FishingBoat
        caption: 2021-03 ~ 진행중
        link: <a href='https://play.google.com/store/apps/details?id=com.OPCStudio.FishingSpot' target='_blank' style='font-size:14px; text-decoration:none;'>피싱보트</a> 
        description: | 
          설명 : 상용화를 목표로 3d 모바일 인디게임 2인 개발 <br />
          담당 : 마이크로 서비스 기반 API 서버(Flask), 언리얼 클라이언트 서브 메뉴 인터페이스 개발, AWS DynamoDB 구축 및 관리, Google Play 관리 <br />
          <mark>Unreal Engine</mark> <mark>C++</mark> <mark>Flask</mark> <mark>AWS</mark> <mark>AWS DynamoDB</mark> <mark>Google Play</mark>

# Education
  - title: Education
    layout: text
    content: |
      <ul>
      <li>모의해킹 침해대응 정보보안전문가<br /><i>솔데스크</i>&nbsp;&nbsp;&nbsp;&nbsp;2021-03 ~ 2021-09 (6mths)</li>
      <li>포항제철공업고등학교<br /><i>컴퓨터네트워크과</i>&nbsp;&nbsp;&nbsp;&nbsp;<i>2006 ~ 2009 (3yrs)</i></li>
      </ul>

# Certificate
  - title: Certificate
    layout: text
    content: |
      <ul>
      <li>정보처리기사&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i>2022-06-17</i> </li>
      <li>SQLD&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i>2022-04-08</i> </li>
      <li>정보보안기사&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i>2016-06-24</i> </li>
      <li>CCNP&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i>2008-03-08(Expired)</i> </li>
      </ul>

# Award-Winning
  - title: Award-Winning
    layout: text
    content: |
      <ul>
      <li>2008년 전국기능경기대회(정보통신)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>동상</b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i>2008-09-30</i> </li>
      <li>2008년 경북지방기능경기대회(정보통신)&nbsp;&nbsp;&nbsp;&nbsp;<b>금상</b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i>2008-04-16</i> </li>
      <li>2007년 전국기능경기대회(정보통신)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>우수상</b>&nbsp;&nbsp;&nbsp;&nbsp;<i>2007-09-15</i> </li>
      <li>2007년 경북지방기능경기대회(정보통신)&nbsp;&nbsp;&nbsp;&nbsp;<b>동상</b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i>2007-04-16</i> </li>
      </ul>

# About more me
  - title: A Little More About Me
    layout: text
    content: | 
      <ul>
      <li>다양한 사람들과 술자리를 가지는 것을 좋아합니다. (호주와 캐나다에서 2년 정도 바텐더로 일했습니다.)</li>
      <li>특기는 요리이고, 음식를 대접해주는 것을 좋아합니다. (호주에서 1년 정도 레스토랑에서 쉐프로 일했습니다)</li>
      <li>취미로 모바일게임을 만들고 있습니다.</li>
      <li>축구를 좋아하고, 맨체스터시티 팬입니다.</li>
      <li>책은 주로 일본 문학을 많이 읽습니다. (좋아하는 작가는 히가시노 게이고)</li>
      <li>운동은 가리지 않고 좋아하며, 요즘은 크로스핏 및 테니스에 빠져 있습니다.</li>
      </ul>

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
